Grima: GrimaTask Class Reference
GrimaTask Class Reference
The base class for most "grimas".
Public Member Functions
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
__construct ()
setup_splat ()
print_form ()
print_success ()
print_failure ()
check_login ()
addMessage ($type, $message)
run ()
get_input ()
check_input ()
get_input_param ($param)
do_task ()
usage ()
Static Public Member Functions
static RunIt ()
static call ($grimaname, $args=array())
Public Attributes
$error = false
$args = array()
$el_override = array()
$auto_args = array()
$messages = array()
Detailed Description
The base class for most "grimas".
Definition at line 1174 of file grima-lib.php.
Constructor & Destructor Documentation
__construct()
GrimaTask::__construct ()
Definition at line 1200 of file grima-lib.php.
References join_paths().
{
         $webroot = __DIR__;
         $base = get_class($this); //basename($_SERVER['PHP_SELF'],'.php');
         if (file_exists(join_paths($webroot,$base,"$base.xml")) and (!isset($this->formxml))) {
             $this->formxml = file_get_contents(join_paths($webroot,$base,"$base.xml"));
         }
         if (isset($this->formxml)) {
             $this->form = new GrimaForm();
             $this->form->fromXML($this->formxml);
         }
     }
Member Function Documentation
addMessage()
GrimaTask::addMessage ($type, $message)
Definition at line 1264 of file grima-lib.php.
Referenced by run().
{
         $this->messages[] = new GrimaTaskMessage($type,$message);
     }
call()
static GrimaTask::call ($grimaname, $args = array()) static
Definition at line 1398 of file grima-lib.php.
References $args, and do_redirect().
{
         $url = rtrim("../$grimaname/$grimaname.php?" . http_build_query($args),"?");
         do_redirect($url);
     }
check_input()
GrimaTask::check_input ()
Definition at line 1325 of file grima-lib.php.
Referenced by get_input_param(), and run().
{
         if (isset($this->form)) {
             $input_good = true;
             foreach ($this->form->fields as $field) {
                 if ($field->required) {
                     if (!isset($this[$field->name]) or
                             !($this[$field->name])) {
                         $field->error_condition = "error";
                         $field->error_message = "Field is required\n";
                         $input_good = false;
                     }
                 }
             }
             return $input_good;
         } else {
             foreach ($this->auto_args as $k => $v) {
                 if (preg_match('/[^:]:$/',$k)) {
                     if (!isset($this->args[$v]) or !($this->args[$v])) {
                         return false;
                     }
                 }
             }
             return true;
         }
     }
check_login()
GrimaTask::check_login ()
Definition at line 1252 of file grima-lib.php.
References $grima, and do_redirect().
Referenced by run().
{
         global $grima;
         if (isset($grima->apikey) and isset($grima->server) and
             ($grima->apikey) and ($grima->server)) {
             return true;
         } else {
             do_redirect('../Login/Login.php?redirect_url=' . urlencode($_SERVER['PHP_SELF']));
             exit;
             return false;
         }
     }
do_task()
GrimaTask::do_task () abstract
Referenced by run().
get_input()
GrimaTask::get_input ()
Definition at line 1296 of file grima-lib.php.
References get_input_param().
Referenced by run().
{
         if (isset($this->form)) {
             if (php_sapi_name() == "cli") { # command line
                 /*
                 if ($options = getopt(implode(array_keys($param)))) {
                     foreach ($param as $k => $v) {
                         $this->args[$v] = $options[$k[0]];
                     }
                     if (!$this->check_input()) {
                         $this->usage(); exit;
                     }
                 } else {
                     $this->usage(); exit;
                 }
                 */
             } else { # web
                 foreach ($this->form->fields as $field) {
                     if (isset($_REQUEST[$field->name])) {
                         $this[$field->name] = $_REQUEST[$field->name];
                         /* sanitize */
                     }
                 }
             }
         } else {
             $this->get_input_param($this->auto_args);
         }
     }
get_input_param()
GrimaTask::get_input_param ($param)
Definition at line 1352 of file grima-lib.php.
References check_input(), print_form(), and usage().
Referenced by get_input().
{
         if (php_sapi_name() == "cli") { # command line
             if ($options = getopt(implode(array_keys($param)))) {
                 foreach ($param as $k => $v) {
                     $this->args[$v] = $options[$k[0]];
                 }
                 if (!$this->check_input()) {
                     $this->usage(); exit;
                 }
             } else {
                 $this->usage(); exit;
             }
         } else { # web
             foreach ($param as $k => $v) {
                 if (isset($_REQUEST[$v])) {
                     $this->args[$v] = $_REQUEST[$v];
                 }
             }
             if (!$this->check_input()) {
                 $this->print_form(); exit;
             }
         }
     }
offsetExists()
GrimaTask::offsetExists ($offset)
Definition at line 1184 of file grima-lib.php.
{
         return isset($this->args[$offset]);
     }
offsetGet()
GrimaTask::offsetGet ($offset)
Definition at line 1188 of file grima-lib.php.
{
         return $this->args[$offset];
     }
offsetSet()
GrimaTask::offsetSet ($offset, $value)
Definition at line 1192 of file grima-lib.php.
{
         $this->args[$offset] = $value;
     }
offsetUnset()
GrimaTask::offsetUnset ($offset)
Definition at line 1196 of file grima-lib.php.
{
         unset($this->args[$offset]);
     }
print_failure()
GrimaTask::print_failure ()
Definition at line 1247 of file grima-lib.php.
Referenced by run().
{
         $this->form->loadValues($this);
         $this->splat->splat('print_failure', $this->splatVars );
     }
print_form()
GrimaTask::print_form ()
Definition at line 1237 of file grima-lib.php.
Referenced by get_input_param(), and run().
{
         $this->form->loadValues($this);
         $this->splat->splat('print_form', $this->splatVars );
     }
print_success()
GrimaTask::print_success ()
Definition at line 1242 of file grima-lib.php.
Referenced by run().
{
         $this->form->loadPersistentValues($this);
         $this->splat->splat('print_success', $this->splatVars );
     }
run()
GrimaTask::run ()
Definition at line 1268 of file grima-lib.php.
References addMessage(), check_input(), check_login(), do_task(), get_input(), print_failure(), print_form(), print_success(), and setup_splat().
{
         $this->check_login(); # if not logged in, print login form
         $this->error = false;
         $this->get_input();
         $this->setup_splat(); # should happen after form xml read in get_input
         if ($this->check_input()) {
             try {
                 $this->do_task();
             } catch (Exception $e) {
                 $this->addMessage('error',$e->getMessage());
                 $this->error = true;
             }
         } else {
             $this->print_form();
             exit;
         }
         if ($this->error) {
             $this->print_failure();
         } else {
             $this->print_success();
         }
     }
RunIt()
static GrimaTask::RunIt () static
Definition at line 1291 of file grima-lib.php.
{
         $task = new static();
         $task->run();
     }
setup_splat()
GrimaTask::setup_splat ()
Definition at line 1212 of file grima-lib.php.
Referenced by run().
{
         $webroot = __DIR__;
         $basename = get_class($this); //basename($_SERVER['PHP_SELF'],'.php');
         $this->splat = new zemowsplat\Splat();
         $this->splat->addBases(array(
             "$webroot/$basename/splats",    // per-task overrides
             "$webroot/splats",              // default
         ));
         $this->splatVars = array(
             'title'             => $this->form->title,
             'basename'          => $basename,
             'webroot'           => $webroot,
             'local_stylesheets' => array('Grima.css'),
             'form'              => &$this->form,
             'messages'          => &$this->messages,
             'width'             => 9,
         );
         if (isset($this['redirect_url'])) {
             $this->splatVars['redirect_url'] = $this['redirect_url'];
         }
     }
usage()
GrimaTask::usage ()
Definition at line 1378 of file grima-lib.php.
Referenced by get_input_param().
                      { # XXX rewrite for grima form
         global $argv;
         print "Usage: php ${argv[0]} ";
         foreach ($this->auto_args as $k => $v) {
             if (preg_match('/^(.):$/',$k,$m)) {
                 print "-${m[1]} <$v> ";
             } else {
                 if (preg_match('/^(.)::$/',$k,$m)) {
                     print "[ -${m[1]} <$v> ] ";
                 } else {
                     if (preg_match('/^.$/',$k)) {
                         print "[ -$k ] ";
                     }
                 }
             }
         }
         print "\n";
         exit;
     }
Member Data Documentation
$args
GrimaTask::$args = array()
Definition at line 1177 of file grima-lib.php.
Referenced by call().
$auto_args
GrimaTask::$auto_args = array()
Definition at line 1180 of file grima-lib.php.
$el_override
GrimaTask::$el_override = array()
Definition at line 1178 of file grima-lib.php.
$error
GrimaTask::$error = false
Definition at line 1176 of file grima-lib.php.
$messages
GrimaTask::$messages = array()
Definition at line 1182 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php