Grima: Item Class Reference
Item Class Reference
class Item
Public Member Functions
loadFromAlma ($mms_id, $holding_id, $item_pid)
populates item record from Alma
loadFromAlmaX ($item_pid)
populates item record from Alma, only needs item_pid
loadFromAlmaBarcode ($barcode)
populates item record from Alma, using barcode
loadFromAlmaBCorX ($id)
populates item record from Alma using either identifier
loadFromItemListNode ($node)
populate item record from the information in an ItemList node
addToAlmaHolding ($mms_id, $holding_id)
add new item record to holding in Alma
updateAlma ()
replace item record in Alma
deleteFromAlma ($override="false", $holdings="retain")
delete record from Alma
Public Member Functions inherited from AlmaObject
__construct ()
create new blank Alma Object
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Attributes
$el_address
Public Attributes inherited from AlmaObject
$el_access = array()
$xml
$templateDir = __DIR__ . "/templates"
Detailed Description
class Item
Definition at line 2435 of file grima-lib.php.
Member Function Documentation
addToAlmaHolding()
Item::addToAlmaHolding ($mms_id, $holding_id)
add new item record to holding in Alma
Parameters
string $mms_id MMS ID of bib record
string $holding_id Holding ID of holding record to add item to
Returns
DomDocument item object as it now appears in Alma
Definition at line 2569 of file grima-lib.php.
References $grima, and AlmaObject\$xml.
{
         global $grima;
         $this->mms_id = $mms_id;
         $this->holding_id = $holding_id;
         $this->xml = $grima->postItem($mms_id,$holding_id,$this->xml);
         return $this->xml;
     }
deleteFromAlma()
Item::deleteFromAlma ($override = "false", $holdings = "retain")
delete record from Alma
Parameters
string $override should the item be deleted even if warnings exist? (default false)
string $holdings method for handling holdings record left with no items (retain, delete, suppress)
Definition at line 2601 of file grima-lib.php.
References $grima.
{
         global $grima;
         $grima->deleteItem($this['mms_id'],$this['holding_id'],$this['item_pid'],$override,$holdings);
     }
loadFromAlma()
Item::loadFromAlma ($mms_id, $holding_id, $item_pid)
populates item record from Alma
Parameters
string $mms_id MMS ID of bib record
string $holding_id Holding ID of holding record
string $item_pid Item ID of item record
Definition at line 2504 of file grima-lib.php.
References $grima.
{
         global $grima;
         $this->xml = $grima->getItem($mms_id,$holding_id,$item_pid);
     }
loadFromAlmaBarcode()
Item::loadFromAlmaBarcode ($barcode)
populates item record from Alma, using barcode
Parameters
string $barcode barcode of record to load from Alma
Definition at line 2526 of file grima-lib.php.
References $grima.
Referenced by loadFromAlmaBCorX().
{
         global $grima;
         $this->xml = $grima->getItemBC($barcode);
     }
loadFromAlmaBCorX()
Item::loadFromAlmaBCorX ($id)
populates item record from Alma using either identifier
Parameters
string $id identifer of record to load from Alma (can be barcode or item ID)
Definition at line 2539 of file grima-lib.php.
References $grima, loadFromAlmaBarcode(), and loadFromAlmaX().
{
         global $grima;
         if (preg_match("/^23.*/",$id)) { # item_pid
             # probably should know about suffix too
             $this->loadFromAlmaX($id);
         } else {
             $this->loadFromAlmaBarcode($id);
         }
     }
loadFromAlmaX()
Item::loadFromAlmaX ($item_pid)
populates item record from Alma, only needs item_pid
Parameters
string $item_pid item ID of record to load from Alma
Definition at line 2515 of file grima-lib.php.
References $grima.
Referenced by loadFromAlmaBCorX().
{
         global $grima;
         $this->xml = $grima->getItem('X','X',$item_pid);
     }
loadFromItemListNode()
Item::loadFromItemListNode ($node)
populate item record from the information in an ItemList node
Parameters
DomNode $node node from an ItemList
Definition at line 2556 of file grima-lib.php.
{
         $this->xml = new DomDocument();
         $this->xml->appendChild($this->xml->importNode($node,true));
     }
updateAlma()
Item::updateAlma ()
replace item record in Alma
Returns
DomDocument item object as it now appears in Alma
Definition at line 2583 of file grima-lib.php.
References $grima.
{
         global $grima;
         return $grima->putItem(
             $this['mms_id'],
             $this['holding_id'],
             $this['item_pid'],
             $this->xml
         );
     }
Member Data Documentation
$el_address
Item::$el_address
Definition at line 2437 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php