Grima: Holding Class Reference
Holding Class Reference
class Holding
Public Member Functions
offsetSet ($offset, $value)
offsetGet ($offset)
loadFromAlma ($mms_id, $holding_id)
populates the record from Alma
getMmsIfNeeded ()
populates the MMS ID if not already known
loadFromAlmaX ($holding_id)
populates the record from Alma - only requires holding_id
addToAlmaBib ($mms_id)
adds a new holding record to the specified bib
updateAlma ()
update holding record in Alma
deleteFromAlma ()
delete the holding record from Alma
setCallNumber ($h, $i, $ind1)
moveToBib ($mms_id)
moves the holding from one bib to another – only for empty holdings!
getItems ()
populate items property with Items objects ## XXX TEST
getItemList ()
populates itemList property from Alma
deleteTreeFromAlma ()
delete the holding and all of its items
Public Member Functions inherited from AlmaObjectWithMARC
appendField ($tag, $ind1, $ind2, $subfields)
add a field to the MARC record
getFields ($tag)
get fields for the given MARC tag
getSubfieldValues ($tag, $code)
get subfield value
deleteField ($tag)
delete all $tag fields from the MARC record
deleteSubfieldMatching ($tag, $code, $regex)
delete subfields matching a regex
replaceOrAddSubfield ($tag, $code, $value)
replace or add subfield value in marc
Public Member Functions inherited from AlmaObject
__construct ()
create new blank Alma Object
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Static Public Member Functions
static getMmsFromHoldingID ($holding_id)
populates the MMS ID
Public Attributes
$itemList
$items = array()
$xml
$el_address
Public Attributes inherited from AlmaObject
$el_access = array()
$xml
$templateDir = __DIR__ . "/templates"
Detailed Description
class Holding
Definition at line 2176 of file grima-lib.php.
Member Function Documentation
addToAlmaBib()
Holding::addToAlmaBib ($mms_id)
adds a new holding record to the specified bib
Parameters
string $mms_id bib record to add the holdings record
Definition at line 2299 of file grima-lib.php.
References $grima.
Referenced by moveToBib().
{
         global $grima;
         $this->xml = $grima->postHolding($mms_id,$this->xml);
         $this['mms_id'] = $mms_id;
     }
deleteFromAlma()
Holding::deleteFromAlma ()
delete the holding record from Alma
Definition at line 2320 of file grima-lib.php.
References $grima.
Referenced by deleteTreeFromAlma(), and moveToBib().
{
         global $grima;
         $grima->deleteHolding($this['mms_id'],$this['holding_id']);
     }
deleteTreeFromAlma()
Holding::deleteTreeFromAlma ()
delete the holding and all of its items
Definition at line 2396 of file grima-lib.php.
References $grima, deleteFromAlma(), and getItemList().
{
         global $grima;
         $this->getItemList();
         foreach ($this->itemList->items as $item) {
             $item->deleteFromAlma("true");
         }
         $this->deleteFromAlma();
     }
getItemList()
Holding::getItemList ()
populates itemList property from Alma
Definition at line 2385 of file grima-lib.php.
References $grima, and getMmsIfNeeded().
Referenced by deleteTreeFromAlma(), and getItems().
{
         global $grima;
         $this->getMmsIfNeeded();
         $this->itemList = new ItemList($this['mms_id'],$this['holding_id']);
     }
getItems()
Holding::getItems ()
populate items property with Items objects ## XXX TEST
Definition at line 2375 of file grima-lib.php.
References getItemList().
{
         $this->getItemList();
         $this->items =& $this->itemList->items;
     }
getMmsFromHoldingID()
static Holding::getMmsFromHoldingID ($holding_id) static
populates the MMS ID
Definition at line 2243 of file grima-lib.php.
References $grima.
Referenced by getMmsIfNeeded(), and loadFromAlmaX().
{
         global $grima;
         $report = new AnalyticsReport();
         $report->path = "/shared/UK Libraries- University of Kentucky (UKY)/Reports/Kathryn/HoldingToMMS";
         $report->filter = '
 <sawx:expr xsi:type="sawx:comparison" op="equal" xmlns:saw="com.siebel.analytics.web/report/v1.1"
 xmlns:sawx="com.siebel.analytics.web/expression/v1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <sawx:expr xsi:type="sawx:sqlExpression">"Holding Details"."Holding Id"</sawx:expr><sawx:expr xsi:type="xsd:string">{holding_id}</sawx:expr>
 </sawx:expr>';
         $report->runReport(array('holding_id' => $holding_id), 1);
         if (count($report->rows) == 1) {
             return $report->rows[0][1];
         } else {
             return null;
         }
     }
getMmsIfNeeded()
Holding::getMmsIfNeeded ()
populates the MMS ID if not already known
Definition at line 2269 of file grima-lib.php.
References $grima, and getMmsFromHoldingID().
Referenced by getItemList().
{
         global $grima;
         if (!isset($this['mms_id']) or (!$this['mms_id'])) {
             $this['mms_id'] = Holding::getMmsFromHoldingID($this['holding_id']);
         }
     }
loadFromAlma()
Holding::loadFromAlma ($mms_id, $holding_id)
populates the record from Alma
Parameters
$mms_id MMS ID of bib record
$holding_id Holding ID of holding
Definition at line 2231 of file grima-lib.php.
References $grima.
{
         global $grima;
         $this->xml = $grima->getHolding($mms_id,$holding_id);
         $this['mms_id'] = $mms_id;
     }
loadFromAlmaX()
Holding::loadFromAlmaX ($holding_id)
populates the record from Alma - only requires holding_id
Parameters
$holding_id Holding ID of holding
Definition at line 2284 of file grima-lib.php.
References $grima, and getMmsFromHoldingID().
{
         global $grima;
         $mms_id = Holding::getMmsFromHoldingID($holding_id);
         $this->xml = $grima->getHolding($mms_id,$holding_id);
         $this['mms_id'] = $mms_id;
     }
moveToBib()
Holding::moveToBib ($mms_id)
moves the holding from one bib to another – only for empty holdings!
Definition at line 2365 of file grima-lib.php.
References addToAlmaBib(), and deleteFromAlma().
{
         $this->deleteFromAlma();
         $this->addToAlmaBib($mms_id);
     }
offsetGet()
Holding::offsetGet ($offset)
Definition at line 2189 of file grima-lib.php.
References AlmaObjectWithMARC\getSubfieldValues().
                                 { #XXX TEST
         if ($offset == "library") {
             $lib = new Library();
             $lib->loadFromAlma($this['library_code']);
             return $lib['name'];
         }
         if ($offset == "location") {
             $loc = new Location();
             $loc->loadFromAlma($this['library_code'],$this['location_code']);
             return $loc['name'];
         }
         if ($offset == "call_number") {
             $Hs = $this->getSubfieldValues("852","h");
             $Is = $this->getSubfieldValues("852","i");
             $acc = "";
             foreach ($Hs as $h) {
                 $acc .= "$h ";
             }
             foreach ($Is as $i) {
                 $acc .= "$i ";
             }
             return rtrim($acc);
         }
         return parent::offsetGet($offset);
     }
offsetSet()
Holding::offsetSet ($offset, $value)
Definition at line 2181 of file grima-lib.php.
{
         if ($offset == "mms_id") {
             $this->el_override['mms_id'] = $value;
         } else {
             parent::offsetSet($offset,$value);
         }
     }
setCallNumber()
Holding::setCallNumber ($h, $i, $ind1)
Definition at line 2341 of file grima-lib.php.
References appendInnerXML().
{
         $xpath = new DomXpath($this->xml);
         $xpath->query("//record/datafield[@tag='852']")->item(0)->setAttribute("ind1",$ind1);
         $field852 = $xpath->query("//record/datafield[@tag='852']")->item(0);
         $subfieldHs = $xpath->query("subfield[@code='h']",$field852);
         foreach ($subfieldHs as $subfieldH) {
             $subfieldH->parentNode->removeChild($subfieldH);
         }
         $subfieldIs = $xpath->query("subfield[@code='i']",$field852);
         foreach ($subfieldIs as $subfieldI) {
             $subfieldI->parentNode->removeChild($subfieldI);
         }
         appendInnerXML($field852,"<subfield code=\"h\">$h</subfield>");
         if ($i) {
             appendInnerXML($field852,"<subfield code=\"i\">$i</subfield>");
         }
     }
updateAlma()
Holding::updateAlma ()
update holding record in Alma
Definition at line 2310 of file grima-lib.php.
References $grima.
{
         global $grima;
         $grima->putHolding($this['mms_id'],$this['holding_id'],$this->xml);
     }
Member Data Documentation
$el_address
Holding::$el_address
Initial value:
= array(
        'holding_id' => '//holding_id',
        'inst_code' => "/holding/record/datafield[@tag='852']/subfield[@code='a']",
        'library_code' => "/holding/record/datafield[@tag='852']/subfield[@code='b']",
        'location_code' => "/holding/record/datafield[@tag='852']/subfield[@code='c']",
    )
Definition at line 2216 of file grima-lib.php.
$itemList
Holding::$itemList
Definition at line 2177 of file grima-lib.php.
$items
Holding::$items = array()
Definition at line 2178 of file grima-lib.php.
$xml
Holding::$xml
Definition at line 2179 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php