Grima: ElectronicService Class Reference
ElectronicService Class Reference
class ElectronicService
Public Member Functions
__construct ()
offsetSet ($offset, $value)
loadFromAlma ($collection_id, $service_id)
load record from Alma
loadFromServiceListNode ($node)
populate item record from the information in an ServiceList node
retrieveAllPortfolios ()
getPortfolios ($limit=10, $offset=0)
get list of portfolios from Alma
deleteAllPortfolios ($bib_treat)
delete all portfolios from the service
Public Member Functions inherited from AlmaObject
__construct ()
create new blank Alma Object
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Attributes
$number_of_portfolios
$portfolios = array()
$el_address
$el_override = array()
Public Attributes inherited from AlmaObject
$el_access = array()
$xml
$templateDir = __DIR__ . "/templates"
Detailed Description
class ElectronicService
Definition at line 2663 of file grima-lib.php.
Constructor & Destructor Documentation
__construct()
ElectronicService::__construct ()
Definition at line 2675 of file grima-lib.php.
{
         # load from template
     }
Member Function Documentation
deleteAllPortfolios()
ElectronicService::deleteAllPortfolios ($bib_treat)
delete all portfolios from the service
Parameters
string $bib_treat - for bibs with no inventory, "retain" or "delete"
Definition at line 2753 of file grima-lib.php.
References $grima, and getPortfolios().
{
         global $grima;
         while ($this->getPortfolios(100,0)) {
             foreach($this->portfolios as $portfolio) {
                 $portfolio->deleteFromAlma($bib_treat);
             }
             $this->portfolios = array();
             sleep(2);
         }
     }
getPortfolios()
ElectronicService::getPortfolios ($limit = 10, $offset = 0)
get list of portfolios from Alma
Parameters
Int $limit max to download (default 10, max 100)
Int $offset starting point in list for download
Returns
Int number of portfolios retrieved
Definition at line 2732 of file grima-lib.php.
References $grima.
Referenced by deleteAllPortfolios(), and retrieveAllPortfolios().
{
         global $grima;
         $ret = $grima->getElectronicPortfoliosForService($this['collection_id'],$this['service_id'],$limit,$offset);
         $xpath = new DOMXpath($ret);
         $ports = $xpath->query('//portfolio');
         foreach ($ports as $portnode) {
             $newport = new ElectronicPortfolio();
             $newport->loadFromPortfolioListNode($portnode);
             $this->portfolios[] = $newport;
         }
         return count($ports);
     }
loadFromAlma()
ElectronicService::loadFromAlma ($collection_id, $service_id)
load record from Alma
Definition at line 2692 of file grima-lib.php.
References $grima.
{
         global $grima;
         $this->xml = $grima->getElectronicService($collection_id,$service_id);
         $this['collection_id'] = $collection_id;
     }
loadFromServiceListNode()
ElectronicService::loadFromServiceListNode ($node)
populate item record from the information in an ServiceList node
Parameters
DomNode $node node from an ItemList
Definition at line 2705 of file grima-lib.php.
{
         $this->xml = new DomDocument();
         $this->xml->appendChild($this->xml->importNode($node,true));
         $xpath = new DomXPath($this->xml);
         $service_link = $xpath->query('//electronic_service')->item(0)->attributes['link']->nodeValue;
         preg_match('!/e-collections/(.*)/e-services/!',$service_link,$m);
         $this['collection_id'] = $m[1];
     }
offsetSet()
ElectronicService::offsetSet ($offset, $value)
Definition at line 2679 of file grima-lib.php.
{
         if ($offset == "collection_id") {
             $this->el_override['collection_id'] = $value;
         } else {
             parent::offsetSet($offset,$value);
         }
     }
retrieveAllPortfolios()
ElectronicService::retrieveAllPortfolios ()
Definition at line 2714 of file grima-lib.php.
References getPortfolios().
{
         $curr_offset = 0;
         do {
             $retrieved = $this->getPortfolios(100, $curr_offset);
             $curr_offset += 100;
         } while ($retrieved == 100);
     }
Member Data Documentation
$el_address
ElectronicService::$el_address
Initial value:
= array(
        'id' => '//id',
        'service_id' => '//id',
    )
Definition at line 2668 of file grima-lib.php.
$el_override
ElectronicService::$el_override = array()
Definition at line 2673 of file grima-lib.php.
$number_of_portfolios
ElectronicService::$number_of_portfolios
Definition at line 2664 of file grima-lib.php.
$portfolios
ElectronicService::$portfolios = array()
Definition at line 2666 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php