Grima: Grima Class Reference
Grima Class Reference
grima-lib.php - a library for running API calls in Alma
Public Member Functions
session_init ($force=false)
session_save ($result)
session_destroy ()
__construct ()
get_config ()
get ($url, $URLparams, $QSparams)
general function for GET (retrieve) API calls
post ($url, $URLparams, $QSparams, $body)
general function for POST (create) API calls
put ($url, $URLparams, $QSparams, $body)
general function for PUT (update) API calls
delete ($url, $URLparams, $QSparams)
general function for DELETE API calls
checkForErrorMessage ($xml)
checks for errorMessage tag, throws exceptions
Bib APIs
getBib ($mms_id, $view='full', $expand='None')
Retrieve Bib - retrieve a bib record from Alma.
postBib ($bib)
Create Record - adds a new bib record to Alma.
putBib ($mms_id, $bib)
Update Bib Record - updates the copy of the bib in Alma.
deleteBib ($mms_id, $override='false')
Delete Bib Record - deletes the bib record from Alma.
Holdings List APIs
getHoldingsList ($mms_id)
Retrieve Holdings list - download brief descriptions of holdings for the bib.
Holding APIs
getHolding ($mms_id, $holding_id)
Retrieve Holdings Record - retrieve holdings record from Alma.
postHolding ($mms_id, $holding)
Create holding record - add a new holdings record to a bib.
putHolding ($mms_id, $holding_id, $holding)
Update Holdings Record - replace the holdings record in Alma.
deleteHolding ($mms_id, $holding_id, $override='false')
Delete Holdings Record - delete the holdings record from Alma.
Item List APIs
getItemList ($mms_id, $holding_id, $limit, $offset)
Retrieve Items list - retrieve the items list from a holding or bib from Alma.
Item APIs
getItem ($mms_id, $holding_id, $item_pid)
Retrieve Item and print label information.
getItemBC ($barcode)
Retrieve Item and print label information (by barcode))
postItem ($mms_id, $holding_id, $item)
Create Item - add a new item to a holding in Alma.
putItem ($mms_id, $holding_id, $item_pid, $item)
Update Item information - replace item record in Alma.
deleteItem ($mms_id, $holding_id, $item_pid, $override="false", $holdings="retain")
Withdraw Item - delete an item record from Alma.
Electronic APIs
getElectronicPortfolio ($collection_id, $service_id, $portfolio_id)
Retrieve Portfolio - retrieve a portfolio record from Alma.
getElectronicPortfolioFromBib ($mms_id, $portfolio_id)
Retrieve Portfolio - retrieve a portfolio record from Alma.
postElectronicPortfolio ($collection_id, $service_id, $portfolio)
Create Electronic Portfolio - add a new portfolio to Alma.
postElectronicPortfolioOnBib ($mms_id, $portfolio)
Create Electronic Portfolio - add a new portfolio to Alma Bib.
putElectronicPortfolioOnBib ($mms_id, $portfolio_id, $portfolio)
Update Electronic Portfolio - update portfolio in Alma.
deleteElectronicPortfolio ($collection_id, $service_id, $portfolio_id)
Delete Electronic Portfolio - delete portfolio from Alma.
getElectronicPortfoliosForService ($collection_id, $service_id, $limit, $offset)
Retrieve Portfolios - retrieve a list of portfolios from Alma.
getElectronicPortfoliosForBib ($mms_id, $limit, $offset)
Retrieve Portfolios list (Bib) - retrieve a list of portfolios from Alma.
getElectronicCollection ($collection_id)
Retrieve Electronic Collection - retrieve a collection record from Alma.
getElectronicServices ($collection_id)
Retrieve Electronic Services - retrieve a list of services from a collection in Alma.
Library APIs
getLibrary ($libraryCode)
Retrieve a Library - retrieve a Library from Alma.
Location APIs
getLocation ($libraryCode, $locationCode)
Retrieve Location - retrieve a Library Location from Alma.
Set APIs
getSet ($set_id)
Retrieve a Set - retrieve a Set from Alma.
createSetFromImport ($job_instance_id, $population)
Create a Set from an import job.
deleteSet ($set_id)
Delete a Set - delete a set (not its items) from Alma.
getSetMembers ($set_id, $limit=10, $offset=0)
get the members of a set, IF IT WORKS?!?!
Analytics APIs
getAnalytics ($path, $filter, $limit=25, $token=null)
Public Attributes
$server
$apikey
Detailed Description
grima-lib.php - a library for running API calls in Alma
(c) 2019 Kathryn Lybarger. CC-BY-SA
Definition at line 14 of file grima-lib.php.
Constructor & Destructor Documentation
__construct()
Grima::__construct ()
Definition at line 60 of file grima-lib.php.
References get_config().
{
         $this->get_config();
     }
Member Function Documentation
checkForErrorMessage()
Grima::checkForErrorMessage ($xml)
checks for errorMessage tag, throws exceptions
Parameters
DomDocument $xml
Definition at line 298 of file grima-lib.php.
Referenced by createSetFromImport(), deleteBib(), deleteElectronicPortfolio(), deleteHolding(), deleteItem(), deleteSet(), getBib(), getElectronicCollection(), getElectronicPortfolio(), getElectronicPortfolioFromBib(), getElectronicPortfoliosForBib(), getElectronicPortfoliosForService(), getElectronicServices(), getHolding(), getHoldingsList(), getItem(), getItemBC(), getItemList(), getLibrary(), getLocation(), getSet(), getSetMembers(), postBib(), postElectronicPortfolio(), postElectronicPortfolioOnBib(), postHolding(), postItem(), putBib(), and putElectronicPortfolioOnBib().
{
         if ($xml instanceOf DomDocument) {
             $xpath = new DomXpath($xml);
             $xpath->registerNamespace("err","http://com/exlibris/urm/general/xmlbeans");
             $error = $xpath->query('//err:errorMessage');
             if ($error->length > 0) {
                 throw new Exception("Alma says: " . $error[0]->nodeValue);
             }
         }
     }
createSetFromImport()
Grima::createSetFromImport ($job_instance_id, $population)
Create a Set from an import job.
Makes a call to the API: (API docs)
POST /almaws/v1/conf/sets
Parameters
string $job_instance_id ID of the import job
string $population ...
Returns
DomDocument Set object
Definition at line 1060 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         # create blank set
         $body = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?' . '>
 <set>
   <name>Grima set from ' . $job_instance_id . '</name>
   <description>members of ' . $job_instance_id . '</description>
   <type desc="Itemized">ITEMIZED</type>
   <content desc="All Titles">BIB_MMS</content>
   <private desc="No">false</private>
 </set>';
 /*
   Content:
     BIB_MMS -- all titles
     ITEM
     PORTFOLIO
     IEPA
     FILE
     AUTHORITY_MMS
     IEP
     IEE
     IED
     IEC
 */
 /*
   Population:
 */
         $bodyxml = new DomDocument();
         $bodyxml->loadXML($body);
         $ret = $this->post('/almaws/v1/conf/sets', array(), array('job_instance_id' => $job_instance_id, 'population' => $population),$bodyxml);
         $this->checkForErrorMessage($ret);
         return $ret;
     }
delete()
Grima::delete ($url, $URLparams, $QSparams)
general function for DELETE API calls
Parameters
string $url - URL pattern string with parameters in {}
array $URLparams - URL parameters
array $QSparams - query string parameters
Definition at line 260 of file grima-lib.php.
{
         foreach ($URLparams as $k => $v) {
             $url = str_replace('{'.$k.'}',urlencode($v),$url);
         }
         $url = $this->server . $url . '?apikey=' . urlencode($this->apikey);
         foreach ($QSparams as $k => $v) {
             $url .= "&$k=$v";
         }
         $ch = curl_init();
         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         curl_setopt($ch, CURLOPT_HEADER, FALSE);
         curl_setopt($ch, CURLOPT_HTTPHEADER,
             array ("Accept: application/xml"));
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
         $response = curl_exec($ch);
         $code = curl_getinfo($ch,CURLINFO_HTTP_CODE);
         if (curl_errno($ch)) {
             throw new Exception("Network error: " . curl_error($ch));
         }
         curl_close($ch);
         if ($code != 204) {
             $xml = new DOMDocument();
             try {
                 $xml->loadXML($response);
             } catch (Exception $e) {
                 throw new Exception("Malformed XML from Alma: $e");
             }
             return $xml;
         }
     }
deleteBib()
Grima::deleteBib ($mms_id, $override = 'false')
Delete Bib Record - deletes the bib record from Alma.
Makes a call to the API: (API docs)
DELETE /almaws/v1/bibs/{mms_id}
Parameters
string $mms_id MMS ID of Alma Bib record to delete
string $override Optional. Default=false
Definition at line 399 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->delete('/almaws/v1/bibs/{mms_id}',
             array('mms_id' => $mms_id),
             array('override' => $override)
         );
         $this->checkForErrorMessage($ret);
     }
deleteElectronicPortfolio()
Grima::deleteElectronicPortfolio ($collection_id, $service_id, $portfolio_id)
Delete Electronic Portfolio - delete portfolio from Alma.
Makes a call to the API: (API docs)
   DELETE /almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios/{portfolio_id}
Parameters
string $collection_id ID of collection
string $service_id ID of service
string $portfolio_id ID of portfolio
Definition at line 849 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->delete('/almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios/{portfolio_id}',
         array('collection_id' => $collection_id, 'service_id' => $service_id, 'portfolio_id' => $portfolio_id),
         array()
         );
         $this->checkForErrorMessage($ret);
     }
deleteHolding()
Grima::deleteHolding ($mms_id, $holding_id, $override = 'false')
Delete Holdings Record - delete the holdings record from Alma.
Makes a call to the API: (API docs)
DELETE /almaws/v1/bibs/{mms_id}/holdings/{holding_id}
Parameters
string $mms_id MMS ID of Alma Bib record
string $holding_id Holding ID of Holding record to delete from Alma
string $override Optional. Default=false
Definition at line 531 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->delete('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}',
             array(
                 'mms_id' => $mms_id,
                 'holding_id' => $holding_id
             ),
             array('override' => $override)
         );
         $this->checkForErrorMessage($ret);
     }
deleteItem()
Grima::deleteItem ($mms_id, $holding_id, $item_pid, $override = "false", $holdings = "retain")
Withdraw Item - delete an item record from Alma.
Makes a call to the API: (API docs)
DELETE /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}
Parameters
string $mms_id MMS ID of Bib record
string $holding_id Holding ID of holding record
string $item_pid Item ID of item record
string $override Override warnings? (false, true)
string $holdings How to handle holdings with inventory? (retain, delete or suppress)
Definition at line 695 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->delete('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}', array(
                 'mms_id' => $mms_id,
                 'holding_id' => $holding_id,
                 'item_pid' => $item_pid
             ), array(
                 'override' => $override,
                 'holdings' => $holdings
             )
         );
         $this->checkForErrorMessage($ret);
     }
deleteSet()
Grima::deleteSet ($set_id)
Delete a Set - delete a set (not its items) from Alma.
Makes a call to the API: (API docs)
DELETE /almaws/v1/conf/sets/{set_id}
Parameters
string $set_id Set ID
Definition at line 1111 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->delete('/almaws/v1/conf/sets/{set_id}',
             array(
                 'set_id' => $set_id,
             ),
             array()
         );
         $this->checkForErrorMessage($ret);
     }
get()
Grima::get ($url, $URLparams, $QSparams)
general function for GET (retrieve) API calls
Parameters
string $url - URL pattern string with parameters in {}
array $URLparams - URL parameters
array $QSparams - query string parameters
Returns
DomDocument of requested record
Definition at line 130 of file grima-lib.php.
{
         # returns a DOM document
         foreach ($URLparams as $k => $v) {
             $url = str_replace('{'.$k.'}',urlencode($v),$url);
         }
         $url = $this->server . $url . '?apikey=' . urlencode($this->apikey);
         foreach ($QSparams as $k => $v) {
             $url .= "&$k=$v";
         }
         $ch = curl_init();
         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
         curl_setopt($ch, CURLOPT_HEADER, FALSE);
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
         $response = curl_exec($ch);
         $code = curl_getinfo($ch,CURLINFO_HTTP_CODE);
         if (curl_errno($ch)) {
             throw new Exception("Network error: " . curl_error($ch));
         }
         curl_close($ch);
         $xml = new DOMDocument();
         try {
             if (!preg_match('/^</',$response)) {
                 throw new Exception($url);
             }
             $xml->loadXML($response);
         } catch (Exception $e) {
             throw new Exception("Malformed XML from Alma: $e");
         }
         return $xml;
     }
get_config()
Grima::get_config ()
Definition at line 64 of file grima-lib.php.
References session_init(), and session_save().
Referenced by __construct().
{
         # Precedence:
         # $_REQUEST, $_SESSION, $_SERVER, $_ENV, grima-config.php
         if (isset($_REQUEST['apikey']) and isset($_REQUEST['server']) and
             ($_REQUEST['apikey']) and ($_REQUEST['server'])
         ) {
             $this->session_save( array(
                 'apikey' => $_REQUEST['apikey'],
                 'server' => $_REQUEST['server']
             ) );
             $this->apikey = $_REQUEST['apikey'];
             $this->server = $_REQUEST['server'];
             return true;
         }
         $this->session_init();
         if ( isset($_SESSION) ) {
             session_write_close();
             if(
                 isset($_SESSION['apikey']) and
                 isset($_SESSION['server']) and
                 ($_SESSION['apikey']) and
                 ($_SESSION['server'])
             ) {
                 $this->apikey = $_SESSION['apikey'];
                 $this->server = $_SESSION['server'];
                 return true;
             }
         }
         if ( isset($_SERVER['apikey']) and isset($_SERVER['server']) and
                 ($_SERVER['apikey']) and ($_SERVER['server'])) {
             $this->apikey = $_SERVER['apikey'];
             $this->server = $_SERVER['server'];
             return true;
         }
         if ( isset($_ENV['apikey']) and isset($_ENV['server']) and
                 ($_ENV['apikey']) and ($_ENV['server'])) {
             $this->apikey = $_ENV['apikey'];
             $this->server = $_ENV['server'];
             return true;
         }
         if( file_exists("grima-config.php") ) {
             require('grima-config.php'); # this should set those
             return true;
         }
         return false;
     }
getAnalytics()
Grima::getAnalytics ($path, $filter, $limit = 25, $token = null)
Definition at line 1153 of file grima-lib.php.
{
         return $this->get('/almaws/v1/analytics/reports',
             array(),
             array('path' => urlencode($path), 'filter' => urlencode($filter),
                 'limit' => $limit, 'token' => $token)
         );
     }
getBib()
Grima::getBib ($mms_id, $view = 'full', $expand = 'None')
Retrieve Bib - retrieve a bib record from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}
Parameters
string $mms_id The Bib Record ID.
string $view Optional. Default=full
string $expand Optional. Default=None
Returns
DomDocument Bib object https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 330 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}',
             array('mms_id' => $mms_id),
             array('view' => $view, 'expand' => $expand)
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicCollection()
Grima::getElectronicCollection ($collection_id)
Retrieve Electronic Collection - retrieve a collection record from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/electronic/e-collections/{collection_id}
Parameters
string $collection_id ID of collection
Returns
DomDocument Electronic Collection object
Definition at line 919 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/electronic/e-collections/{collection_id}',
             array('collection_id' => $collection_id),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicPortfolio()
Grima::getElectronicPortfolio ($collection_id, $service_id, $portfolio_id)
Retrieve Portfolio - retrieve a portfolio record from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios/{portfolio_id}
Parameters
string $collection_id ID of collection
string $service_id ID of service
string $portfolio_id ID of portfolio
Returns
DomDocument Electronic Portfolio object
Definition at line 731 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios/{portfolio_id}',
             array('collection_id' => $collection_id, 'service_id' => $service_id, 'portfolio_id' => $portfolio_id),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicPortfolioFromBib()
Grima::getElectronicPortfolioFromBib ($mms_id, $portfolio_id)
Retrieve Portfolio - retrieve a portfolio record from Alma.
Makes a call to the API: (API docs)
 GET /almaws/v1/bibs/{mms_id}/portfolios/{portfolio_id}
Parameters
string $mms_id ID of bib record
string $portfolio_id ID of portfolio
Returns
DomDocument Electronic Portfolio object
Definition at line 754 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/portfolios/{portfolio_id}',
             array('mms_id' => $mms_id, 'portfolio_id' => $portfolio_id),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicPortfoliosForBib()
Grima::getElectronicPortfoliosForBib ($mms_id, $limit, $offset)
Retrieve Portfolios list (Bib) - retrieve a list of portfolios from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}/portfolios
Parameters
string $mms_id ID of bib
string $limit Max number of portfolios to retrieve
string $offset Offset of the results
Returns
DomDocument Portfolios List object
Definition at line 897 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/portfolios',
             array('mms_id' => $mms_id),
             array('limit' => $limit, $offset = $offset)
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicPortfoliosForService()
Grima::getElectronicPortfoliosForService ($collection_id, $service_id, $limit, $offset)
Retrieve Portfolios - retrieve a list of portfolios from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios
Parameters
string $collection_id ID of collection
string $service_id ID of service
string $limit Max number of portfolios to retrieve
string $offset Offset of the results
Returns
DomDocument Retrieve Portfolios object
Definition at line 873 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios',
             array('collection_id' => $collection_id, 'service_id' => $service_id),
             array('limit' => $limit, $offset = $offset)
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getElectronicServices()
Grima::getElectronicServices ($collection_id)
Retrieve Electronic Services - retrieve a list of services from a collection in Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/electronic/e-collections/{collection_id}/e-services
Parameters
string $collection_id ID of collection
Returns
DomDocument Services object
Definition at line 942 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/electronic/e-collections/{collection_id}/e-services',
             array('collection_id' => $collection_id),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getHolding()
Grima::getHolding ($mms_id, $holding_id)
Retrieve Holdings Record - retrieve holdings record from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}/holdings/{holding_id}
Parameters
string $mms_id MMS ID of Alma Bib
string $holding_id Holdings ID of Alma Holding
Returns
DomDocument Holding object
Definition at line 458 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}',
             array(
             'mms_id' => $mms_id,
             'holding_id' => $holding_id
             ),
             array()
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getHoldingsList()
Grima::getHoldingsList ($mms_id)
Retrieve Holdings list - download brief descriptions of holdings for the bib.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}/holdings
Parameters
string $mms_id MMS ID of Alma Bib to gather holdings from
Returns
DomDocument Holdings List object
Definition at line 428 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/holdings',
             array('mms_id' => $mms_id),
             array()
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getItem()
Grima::getItem ($mms_id, $holding_id, $item_pid)
Retrieve Item and print label information.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}
Parameters
string $mms_id MMS ID of Alma Bib
string $holding_id Holding ID of Alma Holding
string $item_pid Item ID of Alma Holding
Definition at line 594 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}', array(
             'mms_id' => $mms_id,
             'holding_id' => $holding_id,
             'item_pid' => $item_pid
             ),
             array()
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getItemBC()
Grima::getItemBC ($barcode)
Retrieve Item and print label information (by barcode))
Makes a call to the API: (API docs)
GET /almaws/v1/items?item_barcode={item_barcode}
Parameters
string $barcode Barcode of Alma item
Definition at line 618 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/items',
             array(),
             array(
                 'item_barcode' => $barcode,
             )
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getItemList()
Grima::getItemList ($mms_id, $holding_id, $limit, $offset)
Retrieve Items list - retrieve the items list from a holding or bib from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items
Parameters
string $mms_id MMS ID of Alma bib
string $holding_id MMS ID of Alma holding
string $limit Max number of items to retrieve
string $offset Offset of the results returned
Returns
DomDocument Item List object
Definition at line 565 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items', array('mms_id' => $mms_id, 'holding_id' => $holding_id),
             array('limit' => $limit, 'offset' => $offset)
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getLibrary()
Grima::getLibrary ($libraryCode)
Retrieve a Library - retrieve a Library from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/conf/libraries/{libraryCode}
Parameters
string $libraryCode ID of the library to retrieve
Returns
DomDocument Library object
Definition at line 971 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/conf/libraries/{libraryCode}',
             array('libraryCode' => $libraryCode),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getLocation()
Grima::getLocation ($libraryCode, $locationCode)
Retrieve Location - retrieve a Library Location from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/conf/libraries/{libraryCode}/locations/{locationCode}
Parameters
string $libraryCode ID of the library to retrieve
Returns
DomDocument Library object
Definition at line 1000 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/conf/libraries/{libraryCode}/locations/{locationCode}',
             array(
                 'libraryCode' => $libraryCode,
                 'locationCode' => $locationCode,
             ),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getSet()
Grima::getSet ($set_id)
Retrieve a Set - retrieve a Set from Alma.
Makes a call to the API: (API docs)
GET /almaws/v1/conf/sets/{set_id}
Parameters
string $set_id ID of the set to retrieve
Returns
DomDocument Set object
Definition at line 1032 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/conf/sets/{set_id}',
             array('set_id' => $set_id),
             array()
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
getSetMembers()
Grima::getSetMembers ($set_id, $limit = 10, $offset = 0)
get the members of a set, IF IT WORKS?!?!
Makes a call to the API: (API docs)
GET /almaws/v1/conf/sets/{set_id}/members
Parameters
string $set_id Set ID
number $limit How many to return at most (default 10)
number $offset Where to start from, for continuation (default 0, the beginning)
Definition at line 1135 of file grima-lib.php.
References checkForErrorMessage().
{
         $ret = $this->get('/almaws/v1/conf/sets/{set_id}/members',
             array('set_id' => $set_id),
             array('limit' => $limit, 'offset' => $offset)
         );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
post()
Grima::post ($url, $URLparams, $QSparams, $body)
general function for POST (create) API calls
Parameters
string $url - URL pattern string with parameters in {}
array $URLparams - URL parameters
array $QSparams - query string parameters
DomDocument $body - object to add to Alma
Returns
DomDocument $body - object as it now appears in Alma
Definition at line 174 of file grima-lib.php.
Referenced by createSetFromImport(), postBib(), postElectronicPortfolio(), postElectronicPortfolioOnBib(), postHolding(), and postItem().
{
         foreach ($URLparams as $k => $v) {
             $url = str_replace('{'.$k.'}',urlencode($v),$url);
         }
         $url = $this->server . $url . '?apikey=' . urlencode($this->apikey);
         foreach ($QSparams as $k => $v) {
             $url .= "&$k=$v";
         }
         $bodyxml = $body->saveXML();
         $ch = curl_init();
         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         curl_setopt($ch, CURLOPT_HEADER, FALSE);
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
         curl_setopt($ch, CURLOPT_POSTFIELDS, $bodyxml);
         curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/xml'));
         $response = curl_exec($ch);
         $code = curl_getinfo($ch,CURLINFO_HTTP_CODE);
         if (curl_errno($ch)) {
             throw new Exception("Network error: " . curl_error($ch));
         }
         curl_close($ch);
         $xml = new DOMDocument();
         try {
             $xml->loadXML($response);
         } catch (Exception $e) {
             throw new Exception("Malformed XML from Alma: $e");
         }
         return $xml;
     }
postBib()
Grima::postBib ($bib)
Create Record - adds a new bib record to Alma.
Makes a call to the API: (API docs)
POST /almaws/v1/bibs
https://developers.exlibrisgroup.com/alma/apis/bibs#Resources
Parameters
DomDocument $bib Bib object to add to Alma as new record
Returns
DomDocument Bib object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 352 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         $ret = $this->post('/almaws/v1/bibs',
             array(),
             array(),
             $bib
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
postElectronicPortfolio()
Grima::postElectronicPortfolio ($collection_id, $service_id, $portfolio)
Create Electronic Portfolio - add a new portfolio to Alma.
Makes a call to the API: (API docs)
POST /almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios/
Parameters
string $collection_id ID of collection
string $service_id ID of service
string $portfolio A portfolio object to add to Alma
Returns
DomDocument Electronic Portfolio object as it appears in Alma
Definition at line 778 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         $ret = $this->post('/almaws/v1/electronic/e-collections/{collection_id}/e-services/{service_id}/portfolios',
             array('collection_id' => $collection_id, 'service_id' => $service_id),
             array(),
             $portfolio
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
postElectronicPortfolioOnBib()
Grima::postElectronicPortfolioOnBib ($mms_id, $portfolio)
Create Electronic Portfolio - add a new portfolio to Alma Bib.
Makes a call to the API: (API docs)
POST /almaws/v1/bibs/{mms_id}/portfolios/
Parameters
string $portfolio_id ID of portfolio
Returns
DomDocument Electronic Portfolio object as it appears in Alma
Definition at line 801 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         $ret = $this->post('/almaws/v1/bibs/{mms_id}/portfolios/',
             array('mms_id' => $mms_id),
             array(),
             $portfolio
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
postHolding()
Grima::postHolding ($mms_id, $holding)
Create holding record - add a new holdings record to a bib.
Makes a call to the API: (API docs)
POST /almaws/v1/bibs/{mms_id}/holdings
Parameters
string $mms_id MMS ID of bib record
DomDocument $holding Holding object to add to Alma as new record
Returns
DomDocument Holding object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 484 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         $ret = $this->post('/almaws/v1/bibs/{mms_id}/holdings',
             array('mms_id' => $mms_id),
             array(),
             $holding
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
postItem()
Grima::postItem ($mms_id, $holding_id, $item)
Create Item - add a new item to a holding in Alma.
Makes a call to the API: (API docs)
POST /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items
Parameters
string $mms_id - MMS ID of Bib record
string $holding_id - Holding ID of Holding record
DomDocument $item - Item object to add to Alma as new record
Returns
DomDocument Bib object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 644 of file grima-lib.php.
References checkForErrorMessage(), and post().
{
         $ret = $this->post('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items',
             array('mms_id' => $mms_id, 'holding_id' => $holding_id),
             array(),
             $item
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
put()
Grima::put ($url, $URLparams, $QSparams, $body)
general function for PUT (update) API calls
Parameters
string $url - URL pattern string with parameters in {}
array $URLparams - URL parameters
array $QSparams - query string parameters
DomDocument $body - record to update Alma record with
Returns
DomDocument - record as it now appears in Alma
Definition at line 218 of file grima-lib.php.
Referenced by putBib(), putElectronicPortfolioOnBib(), putHolding(), and putItem().
{
         foreach ($URLparams as $k => $v) {
             $url = str_replace('{'.$k.'}',urlencode($v),$url);
         }
         $url = $this->server . $url . '?apikey=' . urlencode($this->apikey);
         foreach ($QSparams as $k => $v) {
             $url .= "&$k=$v";
         }
         $bodyxml = $body->saveXML();
         $ch = curl_init();
         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
         curl_setopt($ch, CURLOPT_HEADER, FALSE);
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
         curl_setopt($ch, CURLOPT_POSTFIELDS, $bodyxml);
         curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/xml'));
         $response = curl_exec($ch);
         $code = curl_getinfo($ch,CURLINFO_HTTP_CODE);
         if (curl_errno($ch)) {
             throw new Exception("Network error: " . curl_error($ch));
         }
         curl_close($ch);
         $xml = new DOMDocument();
         try {
             $xml->loadXML($response);
         } catch (Exception $e) {
             throw new Exception("Malformed XML from Alma: $e");
         }
         return $xml;
     }
putBib()
Grima::putBib ($mms_id, $bib)
Update Bib Record - updates the copy of the bib in Alma.
Makes a call to the API: (API docs)
PUT /almaws/v1/bibs/{mms_id}
Parameters
string $mms_id Alma Bib record to update
DomDocument $bib Bib to replace old record
Returns
DomDocument Bib object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 376 of file grima-lib.php.
References checkForErrorMessage(), and put().
{
         $ret = $this->put('/almaws/v1/bibs/{mms_id}',
             array('mms_id' => $mms_id),
             array(),
             $bib
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
putElectronicPortfolioOnBib()
Grima::putElectronicPortfolioOnBib ($mms_id, $portfolio_id, $portfolio)
Update Electronic Portfolio - update portfolio in Alma.
Makes a call to the API: (API docs)
PUT /almaws/v1/bibs/{mms_id}/portfolios/{portfolio_id}
Parameters
string $mms_id ID of bibliographic record
string $portfolio_id ID of portfolio
Returns
DomDocument Electronic Portfolio object as it appears in Alma
Definition at line 825 of file grima-lib.php.
References checkForErrorMessage(), and put().
{
         $ret = $this->put('/almaws/v1/bibs/{mms_id}/portfolios/{portfolio_id}',
             array('mms_id' => $mms_id, 'portfolio_id' => $portfolio_id),
             array(),
             $portfolio
             );
         $this->checkForErrorMessage($ret);
         return $ret;
     }
putHolding()
Grima::putHolding ($mms_id, $holding_id, $holding)
Update Holdings Record - replace the holdings record in Alma.
Makes a call to the API: (API docs)
PUT /almaws/v1/bibs/{mms_id}/holdings/{holding_id}
Parameters
string $mms_id MMS ID of Bib
string $holding_id Holding ID of holding to replace
DomDocument $holding Holding object to add to Alma as new record
Returns
DomDocument Bib object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 509 of file grima-lib.php.
References put().
{
         $ret = $this->put('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}',
             array('mms_id' => $mms_id, 'holding_id' => $holding_id),
             array(),
             $holding
             );
     }
putItem()
Grima::putItem ($mms_id, $holding_id, $item_pid, $item)
Update Item information - replace item record in Alma.
Makes a call to the API: (API docs)
PUT /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}
Parameters
string $mms_id MMS ID of Bib record
string $holding_id Holding ID of Holding record
string $item_pid Item ID of Item record
DomDocument $item Item object to update record with in Alma
Returns
DomDocument Bib object as it now appears in Alma https://developers.exlibrisgroup.com/alma/apis/xsd/rest_bib.xsd?tags=GET
Definition at line 670 of file grima-lib.php.
References put().
{
         $ret = $this->put('/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}',
             array('mms_id' => $mms_id, 'holding_id' => $holding_id, 'item_pid' => $item_pid),
             array(),
             $item
             );
         return $ret;
     }
session_destroy()
Grima::session_destroy ()
Definition at line 43 of file grima-lib.php.
References session_init().
{
         $this->session_init(true);
         session_start();
         if (ini_get("session.use_cookies")) {
             $params = session_get_cookie_params();
             setcookie(session_name(), '', time() - 42000,
                 $params["path"], $params["domain"],
                 $params["secure"], $params["httponly"]
             );
         }
         session_destroy();
         $_SESSION=array();
     }
session_init()
Grima::session_init ($force = false)
Definition at line 20 of file grima-lib.php.
References join_paths().
Referenced by get_config(), session_destroy(), and session_save().
{
         if( !isset($_SESSION) ) {
             $session_name = 'grima';
             $session_dir = join_paths( sys_get_temp_dir(), 'grima' );
             @mkdir($session_dir, 0777, true);
             session_save_path($session_dir);
             session_name( $session_name );
             session_set_cookie_params(365*24*60*60); # one year
             ini_set('session.gc_maxlifetime',525600*60); # of love
             if( $force || isset($_COOKIE[$session_name]) ) {
                 session_start();
             }
         }
     }
session_save()
Grima::session_save ($result)
Definition at line 35 of file grima-lib.php.
References session_init().
Referenced by get_config().
{
         $this->session_init(true);
         foreach( $result as $key => $value ) {
             $_SESSION[$key] = $value;
         }
         session_write_close();
     }
Member Data Documentation
$apikey
Grima::$apikey
Definition at line 16 of file grima-lib.php.
$server
Grima::$server
Definition at line 15 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php