Grima: XMLAsArrayOfDOMNodeListsSpecifiedByXPath Class Reference
XMLAsArrayOfDOMNodeListsSpecifiedByXPath Class Reference
Public Member Functions
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
__construct ($xml, $context_node)
__toString ()
__get (string $name)
__set (string $name, $value)
__isset (string $name)
__unset (string $name)
Additional Inherited Members
Public Attributes inherited from XMLAsArrayOfWhateversSpecifiedByXPath
$xml
$context_node
Protected Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
query (string $offset)
Detailed Description
Definition at line 128 of file grima-xmlbag.php.
Member Function Documentation
offsetExists()
XMLAsArrayOfDOMNodeListsSpecifiedByXPath::offsetExists ($offset)
Definition at line 129 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         return $this->query( $offset )->length > 0; // technically it always exists, but...
     }
offsetGet()
XMLAsArrayOfDOMNodeListsSpecifiedByXPath::offsetGet ($offset)
Definition at line 132 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         return $this->query( $offset );
     }
offsetSet()
XMLAsArrayOfDOMNodeListsSpecifiedByXPath::offsetSet ($offset, $value)
Definition at line 135 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         $cur_length = $nodeList->length;
         $new_length = $value->length;
         for( $i = 0 ; $i < min( $cur_length, $new_length ) ; $i++ ) {
             $cur_node = $nodeList->item($i);
             $new_node = $value->item($i);
             $cur_node->parentNode->replaceChild( $new_node, $cur_node );
         }
         for( $i = min( $cur_length, $new_length ) ; $i < $cur_length ; $i++ ) {
             $cur_node = $nodeList->item($i);
             $cur_node->parentNode->removeChild( $cur_node );
         }
         for( $i = min( $cur_length, $new_length ) ; $i < $new_length ; $i++ ) {
             $new_node = $value->item($i);
             $this->context_node->appendChild( $new_node );
         }
     }
offsetUnset()
XMLAsArrayOfDOMNodeListsSpecifiedByXPath::offsetUnset ($offset)
Definition at line 153 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         $cur_length = $nodeList->length;
         for( $i = 0 ; $i < $cur_length ; $i++ ) {
             $cur_node = $nodeList->item($i);
             $cur_node->parentNode->removeChild( $cur_node );
         }
     }
The documentation for this class was generated from the following file:
grimas/grima-xmlbag.php