Grima: GrimaDB Class Reference
GrimaDB Class Reference
Shared access to the database for GrimaUser and GrimaInstitution.
Public Member Functions
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
getIterator ()
Static Public Member Functions
static init ()
static isEmpty ()
Protected Member Functions
getPasswordAlgorithm ()
Static Protected Member Functions
static getDb ()
Private Attributes
$info
Static Private Attributes
static $db = FALSE
Detailed Description
Shared access to the database for GrimaUser and GrimaInstitution.
Definition at line 3132 of file grima-lib.php.
Member Function Documentation
getDb()
static GrimaDB::getDb () static protected
Definition at line 3158 of file grima-lib.php.
References join_paths().
Referenced by GrimaInstitution\addToDB(), GrimaUser\addToDB(), GrimaUser\deleteFromDB(), and GrimaUser\updateDB().
{
         if (!self::$db) {
             $db_url = getenv('DATABASE_URL');
             if (!$db_url) $db_url = "sqlite:" . join_paths( sys_get_temp_dir(), "grima/grima.sql");
             self::$db = new PDO($db_url);
         }
         return self::$db;
     }
getIterator()
GrimaDB::getIterator ()
Definition at line 3189 of file grima-lib.php.
{
         return new ArrayIterator($this->info);
     }
getPasswordAlgorithm()
GrimaDB::getPasswordAlgorithm () protected
Definition at line 3166 of file grima-lib.php.
Referenced by GrimaUser\addToDB(), and GrimaUser\updateDB().
{
         return defined("PASSWORD_ARGON2I") ? constant("PASSWORD_ARGON2I") : PASSWORD_DEFAULT;
     }
init()
static GrimaDB::init () static
Definition at line 3133 of file grima-lib.php.
References $db, and tableExists().
{
         try {
             $db = self::getDb();
             if (!tableExists($db,"institutions")) {
                 $db->exec("CREATE TABLE institutions ( institution VARCHAR(100) PRIMARY KEY, apikey VARCHAR(100), server VARCHAR(100) )");
             }
             if (!tableExists($db,"users")) {
                 $db->exec("CREATE TABLE users ( institution VARCHAR(100), username VARCHAR(100), password VARCHAR(255), isAdmin BOOLEAN )");
             }
             return true;
         } catch(Exception $x) {
             # create the database
             return false;
         }
     }
isEmpty()
static GrimaDB::isEmpty () static
Definition at line 3148 of file grima-lib.php.
References $db.
{
         self::init();
         $db = self::getDb();
         $result = $db->query( 'SELECT COUNT(*) as c FROM institutions' );
         foreach( $result as $row ) {
             if ($row['c']>0) return false;
         }
         return true;
     }
offsetExists()
GrimaDB::offsetExists ($offset)
Definition at line 3173 of file grima-lib.php.
{
         return isset($this->info[$offset]);
     }
offsetGet()
GrimaDB::offsetGet ($offset)
Definition at line 3177 of file grima-lib.php.
{
         return isset($this->info[$offset]) ? $this->info[$offset] : '';
     }
offsetSet()
GrimaDB::offsetSet ($offset, $value)
Definition at line 3181 of file grima-lib.php.
{
         $this->info[$offset] = $value;
     }
offsetUnset()
GrimaDB::offsetUnset ($offset)
Definition at line 3185 of file grima-lib.php.
{
         unset($this->info[$offset]);
     }
Member Data Documentation
$db
GrimaDB::$db = FALSE static private
Definition at line 3170 of file grima-lib.php.
Referenced by GrimaInstitution\addToDB(), GrimaUser\addToDB(), GrimaUser\deleteFromDB(), init(), isEmpty(), GrimaUser\LookupUser(), GrimaUser\RenameUser(), GrimaUser\ResetPassword(), and GrimaUser\updateDB().
$info
GrimaDB::$info private
Definition at line 3171 of file grima-lib.php.
The documentation for this class was generated from the following file:
grimas/grima-lib.php