Grima: GrimaUser Class Reference
GrimaUser Class Reference
Interface to the GrimaDB database to check password and get institution's apikey.
Public Member Functions
addToDB ()
updateDB ()
deleteFromDB ()
Public Member Functions inherited from GrimaDB
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
getIterator ()
Static Public Member Functions
static FromArray ($data)
static LookupUser ($username, $institution='', $password=FALSE)
static RenameUser ($username, $institution, $newusername)
static ResetPassword ($username, $institution, $password)
static GetCurrentUser ()
static SetCurrentUser ($username, $password, $institution='')
Static Public Member Functions inherited from GrimaDB
static init ()
static isEmpty ()
Additional Inherited Members
Protected Member Functions inherited from GrimaDB
getPasswordAlgorithm ()
Static Protected Member Functions inherited from GrimaDB
static getDb ()
Detailed Description
Interface to the GrimaDB database to check password and get institution's apikey.
Definition at line 3233 of file grima-lib.php.
Member Function Documentation
addToDB()
GrimaUser::addToDB ()
Definition at line 3347 of file grima-lib.php.
References GrimaDB\$db, GrimaDB\getDb(), and GrimaDB\getPasswordAlgorithm().
{
         $db = $this->getDb();
         $query = $db->prepare( 'INSERT INTO users( username, password, institution, isAdmin ) VALUES (:username, :password, :institution, :isAdmin)' );
         if (!$query) {
             $errorCode = $db->errorCode();
             $errorInfo = $db->errorInfo();
             throw new Exception(
                 "Could not even prepare to insert into user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
         $success = $query->execute( array(
             'username' => $this['username'],
             'password' => password_hash( $this['password'], $this->getPasswordAlgorithm() ),
             'institution' => $this['institution'],
             'isAdmin' => $this['isAdmin'],
         ) );
         if (!$success) {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not insert into user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
deleteFromDB()
GrimaUser::deleteFromDB ()
Definition at line 3397 of file grima-lib.php.
References GrimaDB\$db, and GrimaDB\getDb().
{
         $db = $this->getDb();
         $query = $db->prepare( 'DELETE FROM users WHERE username=:username AND institution=:institution' );
         if (!$query) {
             $errorCode = $db->errorCode();
             $errorInfo = $db->errorInfo();
             throw new Exception(
                 "Could not even prepare to delete from user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
         $success = $query->execute( array(
             'username' => $this['username'],
             'institution' => $this['institution'],
         ) );
         if (!$success) {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not delete from user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
FromArray()
static GrimaUser::FromArray ($data) static
Definition at line 3234 of file grima-lib.php.
Referenced by GetCurrentUser(), and LookupUser().
{
         $user = new GrimaUser();
         foreach ( $data as $key => $val ) {
             $user[$key] = $val;
         }
         return $user;
     }
GetCurrentUser()
static GrimaUser::GetCurrentUser () static
Definition at line 3325 of file grima-lib.php.
References $grima, and FromArray().
{
         global $grima;
         $grima->session_init();
         session_write_close();
         if (!isset($_SESSION)) return false;
         return GrimaUser::FromArray( $_SESSION );
     }
LookupUser()
static GrimaUser::LookupUser ($username, $institution = '', $password = FALSE) static
Definition at line 3242 of file grima-lib.php.
References GrimaDB\$db, and FromArray().
Referenced by SetCurrentUser().
{
         $db = self::getDb();
         $query = $db->prepare(
             'SELECT * ' .
             'FROM institutions NATURAL JOIN users '.
             'WHERE institution=:institution '.
             'AND username=:username'
         );
         $success = $query->execute( array(
             'institution' => $institution,
             'username' => $username,
         ) );
         if ($success) {
             $row = $query->fetch(PDO::FETCH_ASSOC);
             if ($row===false) return false;
             $user = GrimaUser::FromArray( $row );
             if ( ($password !== FALSE) && ($user['password']!='') ) {
                 if ( !password_verify( $password, $user['password'] ) ) return false;
                 if ( password_needs_rehash( $user['password'], $user->getPasswordAlgorithm() ) ) {
                     $user['password'] = $password;
                     $user->updateDB();
                 }
             }
             unset( $user['password'] );
             return $user;
         } else {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not select from user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
RenameUser()
static GrimaUser::RenameUser ($username, $institution, $newusername) static
Definition at line 3276 of file grima-lib.php.
References GrimaDB\$db.
{
         $db = self::getDb();
         $query = $db->prepare(
             'UPDATE users ' .
             'SET username=:newusername ' .
             'WHERE institution=:institution '.
             'AND username=:username'
         );
         $success = $query->execute( array(
             'institution'   => $institution,
             'username'      => $username,
             'newusername'   => $newusername,
         ) );
         if ($success) {
             return true;
         } else {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not update user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
ResetPassword()
static GrimaUser::ResetPassword ($username, $institution, $password) static
Definition at line 3300 of file grima-lib.php.
References GrimaDB\$db.
{
         $db = self::getDb();
         $query = $db->prepare(
             'UPDATE users ' .
             'SET password=:password ' .
             'WHERE institution=:institution '.
             'AND username=:username'
         );
         $passwordHash = password_hash( $password, self::getPasswordAlgorithm() );
         $success = $query->execute( array(
             'institution'   => $institution,
             'username'      => $username,
             'password'      => $passwordHash,
         ) );
         if ($success) {
             return true;
         } else {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not update user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
SetCurrentUser()
static GrimaUser::SetCurrentUser ($username, $password, $institution = '') static
Definition at line 3333 of file grima-lib.php.
References $grima, and LookupUser().
{
         global $grima;
         $user = GrimaUser::LookupUser( $username, $institution, $password );
         if ( $user !== false ) {
             if (isset($_SESSION)) {
                 session_write_close();
                 session_start();
             }
             $grima->session_save($user);
         } else {
             return false;
         }
     }
updateDB()
GrimaUser::updateDB ()
Definition at line 3372 of file grima-lib.php.
References GrimaDB\$db, GrimaDB\getDb(), and GrimaDB\getPasswordAlgorithm().
{
         $db = $this->getDb();
         $query = $db->prepare( 'UPDATE users SET isAdmin=:isAdmin, password=:password WHERE username=:username AND institution=:institution' );
         if (!$query) {
             $errorCode = $db->errorCode();
             $errorInfo = $db->errorInfo();
             throw new Exception(
                 "Could not even prepare to update user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
         $success = $query->execute( array(
             'username'  => $this['username'],
             'password'  => password_hash( $this['password'], $this->getPasswordAlgorithm() ),
             'institution' => $this['institution'],
             'isAdmin'   => $this['isAdmin'],
         ) );
         if (!$success) {
             $errorCode = $query->errorCode();
             $errorInfo = $query->errorInfo();
             throw new Exception(
                 "Could not update user database: [$errorCode] {$errorInfo[0]} {$errorInfo[2]}"
             );
         }
     }
The documentation for this class was generated from the following file:
grimas/grima-lib.php