Grima: XMLAsArrayOfWhateversSpecifiedByXPath Class Reference
XMLAsArrayOfWhateversSpecifiedByXPath Class Reference
Public Member Functions
__construct ($xml, $context_node)
__toString ()
__get (string $name)
__set (string $name, $value)
__isset (string $name)
__unset (string $name)
Public Attributes
$xml
$context_node
Protected Member Functions
query (string $offset)
Private Attributes
$xpath = null
Detailed Description
Definition at line 44 of file grima-xmlbag.php.
Constructor & Destructor Documentation
__construct()
XMLAsArrayOfWhateversSpecifiedByXPath::__construct ($xml, $context_node)
Definition at line 48 of file grima-xmlbag.php.
References $context_node, and $xml.
{
         if( is_string( $xml ) ) {
             $this->xml = new DOMDocument();
             $this->xml->loadXML( $xml );
         } elseif( $xml instanceof DOMDocument ) {
             $this->xml = $xml;
         } else {
             throw new Exception("<xml> must be of type DOMDocument in new XMLAsArrayOf...(xml,context)");
         }
         $this->xpath = new DOMXPath($this->xml);
         if( is_string( $context_node ) ) {
             $nodeList = $this->xpath->query( $context_node );
             //print( "Context ($context_node) is: " . xml_debug($nodeList) . "\n" );
             if( $nodeList->length === 1 ) {
                 $this->context_node = $nodeList->item(0);
             } else {
                 $this->context_node = $this->xml->documentElement;
             }
         } elseif( $context_node instanceof DOMElement ) {
             $this->context_node = $context_node;
         } else {
             $this->context_node = $this->xml->documentElement;
         }
     }
Member Function Documentation
__get()
XMLAsArrayOfWhateversSpecifiedByXPath::__get (string $name)
Definition at line 82 of file grima-xmlbag.php.
References query().
{
         $class = get_class($this);
         return new $class( $this->xml, $this->query($name) );
     }
__isset()
XMLAsArrayOfWhateversSpecifiedByXPath::__isset (string $name)
Definition at line 89 of file grima-xmlbag.php.
{
         return isset( $this[$name] );
     }
__set()
XMLAsArrayOfWhateversSpecifiedByXPath::__set (string $name, $value)
Definition at line 86 of file grima-xmlbag.php.
{
         $this[$name] = $value;
     }
__toString()
XMLAsArrayOfWhateversSpecifiedByXPath::__toString ()
Definition at line 79 of file grima-xmlbag.php.
{
         return $this->xml->saveXML( $this->context_node );
     }
__unset()
XMLAsArrayOfWhateversSpecifiedByXPath::__unset (string $name)
Definition at line 92 of file grima-xmlbag.php.
{
         unset( $this[$name] );
     }
query()
XMLAsArrayOfWhateversSpecifiedByXPath::query (string $offset) protected
Definition at line 72 of file grima-xmlbag.php.
Referenced by __get(), XMLAsArrayOfDOMNodesSpecifiedByXPath\offsetExists(), XMLAsArrayOfDOMNodeListsSpecifiedByXPath\offsetExists(), XMLAsArrayOfStringsSpecifiedByXPath\offsetExists(), XMLAsArrayOfDOMNodesSpecifiedByXPath\offsetGet(), XMLAsArrayOfDOMNodeListsSpecifiedByXPath\offsetGet(), XMLAsArrayOfStringsSpecifiedByXPath\offsetGet(), XMLAsArrayOfDOMNodesSpecifiedByXPath\offsetSet(), XMLAsArrayOfDOMNodeListsSpecifiedByXPath\offsetSet(), XMLAsArrayOfStringsSpecifiedByXPath\offsetSet(), XMLAsArrayOfDOMNodesSpecifiedByXPath\offsetUnset(), and XMLAsArrayOfDOMNodeListsSpecifiedByXPath\offsetUnset().
{
         if( isset( $this->context_node ) ) {
             return $this->xpath->query( $offset, $this->context_node );
         } else {
             return $this->xpath->query( $offset );
         }
     }
Member Data Documentation
$context_node
XMLAsArrayOfWhateversSpecifiedByXPath::$context_node
Definition at line 46 of file grima-xmlbag.php.
Referenced by __construct().
$xml
XMLAsArrayOfWhateversSpecifiedByXPath::$xml
Definition at line 45 of file grima-xmlbag.php.
Referenced by __construct().
$xpath
XMLAsArrayOfWhateversSpecifiedByXPath::$xpath = null private
Definition at line 47 of file grima-xmlbag.php.
The documentation for this class was generated from the following file:
grimas/grima-xmlbag.php