Grima: XMLAsArrayOfStringsSpecifiedByXPath Class Reference
XMLAsArrayOfStringsSpecifiedByXPath Class Reference
Public Member Functions
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
__construct ($xml, $context_node)
__toString ()
__get (string $name)
__set (string $name, $value)
__isset (string $name)
__unset (string $name)
Additional Inherited Members
Public Attributes inherited from XMLAsArrayOfWhateversSpecifiedByXPath
$xml
$context_node
Protected Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
query (string $offset)
Detailed Description
Definition at line 163 of file grima-xmlbag.php.
Member Function Documentation
offsetExists()
XMLAsArrayOfStringsSpecifiedByXPath::offsetExists ($offset)
Definition at line 164 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         return $this->query( $offset )->length === 1;
     }
offsetGet()
XMLAsArrayOfStringsSpecifiedByXPath::offsetGet ($offset)
Definition at line 167 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         if( $nodeList->length === 1 ) {
             return $nodeList->item(0)->nodeValue;
         }
     }
offsetSet()
XMLAsArrayOfStringsSpecifiedByXPath::offsetSet ($offset, $value)
Definition at line 173 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         if( $nodeList->length === 1 ) {
             print "Setting!\n";
             $nodeList->item(0)->nodeValue = $value;
         } else if( $nodeList->length === 0 ) {
             $node = $this->xml->createElement( basename($offset) );
             $node->nodeValue = $value;
             $this->contextNode->appendChild( $node );
         }
     }
offsetUnset()
XMLAsArrayOfStringsSpecifiedByXPath::offsetUnset ($offset)
Definition at line 184 of file grima-xmlbag.php.
{
         if( $nodeList->length === 1 ) {
             $node = $nodeList->item(0);
             $node->parentNode->removeChild( $node );
         }
     }
The documentation for this class was generated from the following file:
grimas/grima-xmlbag.php