Grima: XMLAsArrayOfDOMNodesSpecifiedByXPath Class Reference
XMLAsArrayOfDOMNodesSpecifiedByXPath Class Reference
Public Member Functions
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Public Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
__construct ($xml, $context_node)
__toString ()
__get (string $name)
__set (string $name, $value)
__isset (string $name)
__unset (string $name)
Additional Inherited Members
Public Attributes inherited from XMLAsArrayOfWhateversSpecifiedByXPath
$xml
$context_node
Protected Member Functions inherited from XMLAsArrayOfWhateversSpecifiedByXPath
query (string $offset)
Detailed Description
Definition at line 97 of file grima-xmlbag.php.
Member Function Documentation
offsetExists()
XMLAsArrayOfDOMNodesSpecifiedByXPath::offsetExists ($offset)
Definition at line 98 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         return $this->query( $offset )->length === 1;
     }
offsetGet()
XMLAsArrayOfDOMNodesSpecifiedByXPath::offsetGet ($offset)
Definition at line 101 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         if( $nodeList->length === 1 )
             return $nodeList->item(0);
     }
offsetSet()
XMLAsArrayOfDOMNodesSpecifiedByXPath::offsetSet ($offset, $value)
Definition at line 106 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         if( $nodeList->length === 1 ) {
             $node = $nodeList->item(0);
             if($node->parentNode !== NULL) {
                 $node->parentNode->replaceChild( $value, $node );
             }
         } elseif( $nodeList->length === 0 ) {
             $nodeList->context_node->appendChild( $value );
         }
     }
offsetUnset()
XMLAsArrayOfDOMNodesSpecifiedByXPath::offsetUnset ($offset)
Definition at line 117 of file grima-xmlbag.php.
References XMLAsArrayOfWhateversSpecifiedByXPath\query().
{
         $nodeList = $this->query( $offset );
         if( $nodeList->length === 1 ) {
             $node = $nodeList->item(0);
             if($node->parentNode !== NULL) {
                 $node->parentNode->removeChild( $node );
             }
         }
     }
The documentation for this class was generated from the following file:
grimas/grima-xmlbag.php