Grima: AlmaObjectWithMARC Class Reference
AlmaObjectWithMARC Class Reference
Methods for fields and subfields in Alma's MARCXML.
Public Member Functions
appendField ($tag, $ind1, $ind2, $subfields)
add a field to the MARC record
getFields ($tag)
get fields for the given MARC tag
getSubfieldValues ($tag, $code)
get subfield value
deleteField ($tag)
delete all $tag fields from the MARC record
deleteSubfieldMatching ($tag, $code, $regex)
delete subfields matching a regex
replaceOrAddSubfield ($tag, $code, $value)
replace or add subfield value in marc
Public Member Functions inherited from AlmaObject
__construct ()
create new blank Alma Object
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Additional Inherited Members
Public Attributes inherited from AlmaObject
$el_access = array()
$xml
$templateDir = __DIR__ . "/templates"
Detailed Description
Methods for fields and subfields in Alma's MARCXML.
Definition at line 1627 of file grima-lib.php.
Member Function Documentation
appendField()
AlmaObjectWithMARC::appendField ($tag, $ind1, $ind2, $subfields)
add a field to the MARC record
Parameters
string $tag a three character MARC tag
Int $ind1 one digit, first indicator
Int $ind2 second digit, second indicator
Array $subfields each entry of the form $code => $value
Definition at line 1638 of file grima-lib.php.
References appendInnerXML().
Referenced by replaceOrAddSubfield().
{
         $frag = "<datafield ind1=\"$ind1\" ind2=\"$ind2\" tag=\"$tag\">";
         foreach ($subfields as $k => $v) {
             $frag .= "<subfield code=\"$k\">$v</subfield>";
         }
         $frag .= "</datafield>";
         $xpath = new DomXpath($this->xml);
         $record = $xpath->query("//record");
         appendInnerXML($record[0],$frag);
     }
deleteField()
AlmaObjectWithMARC::deleteField ($tag)
delete all $tag fields from the MARC record
Parameters
string $tag a three character MARC tag
Definition at line 1702 of file grima-lib.php.
{
         $xpath = new DomXpath($this->xml);
         $fields = $xpath->query("//record/datafield[@tag='$tag']");
         foreach( $fields as $field ) {
             $field->parentNode->removeChild( $field );
         }
     }
deleteSubfieldMatching()
AlmaObjectWithMARC::deleteSubfieldMatching ($tag, $code, $regex)
delete subfields matching a regex
Parameters
Array $subfields each entry of the form $code => $value
Definition at line 1717 of file grima-lib.php.
{
         $xpath = new DomXPath($this->xml);
         $subfs = $xpath->query("//datafield[@tag='$tag']/subfield[@code='$code']");
         foreach ($subfs as $subf) {
             if (preg_match($regex,$subf->nodeValue)) {
                 $subf->parentNode->removeChild($subf);
             }
         }
     }
getFields()
AlmaObjectWithMARC::getFields ($tag)
get fields for the given MARC tag
Parameters
String $tag field
Returns
Array of MARC fields -> object?
Definition at line 1657 of file grima-lib.php.
{
         $xpath = new DomXpath($this->xml);
         $tag = preg_replace('/X*$/','',$tag);
         $tag = preg_replace('/\.*$/','',$tag);
         $fields = $xpath->query("//record/datafield[starts-with(@tag,'$tag')]");
         $fieldarr = array();
         foreach ($fields as $field) {
             $subfieldarr = array();
             foreach ($field->childNodes as $child) {
                 $subfieldarr[] = array(
                     $child->attributes[0]->value,
                     $child->nodeValue
                 );
             }
             $fieldarr[] = $subfieldarr;
         }
         return $fieldarr;
     }
getSubfieldValues()
AlmaObjectWithMARC::getSubfieldValues ($tag, $code)
get subfield value
Parameters
String $tag field
String $code subfield
Returns
Array array containing all values of subfield
Definition at line 1685 of file grima-lib.php.
Referenced by Holding\offsetGet().
{
         $xpath = new DomXpath($this->xml);
         $subfields = $xpath->query("//record/datafield[@tag='$tag']/subfield[@code='$code']");
         $arr = array();
         foreach ($subfields as $subfield) {
             $arr[] = $subfield->nodeValue;
         }
         return $arr;
     }
replaceOrAddSubfield()
AlmaObjectWithMARC::replaceOrAddSubfield ($tag, $code, $value)
replace or add subfield value in marc
Parameters
string $tag a three character MARC tag
string $code a one letter subfield code
string $value what to set the value to
Definition at line 1736 of file grima-lib.php.
References appendField().
Referenced by Bib\offsetSet().
{
         # very shady but sometimes needed
         $xpath = new DomXpath($this->xml);
         $fields = $xpath->query("//record/datafield[@tag='$tag']");
         if (sizeof($fields) == 0) {
             $this->appendField($tag,' ',' ',array($code => $value));
         } else {
             $done = false;
             foreach  ($fields[0]->childNodes as $subfield) {
                 if($subfield->nodeType !== 1) {
                     continue;
                 }
                 if ($subfield->getAttribute("code") == $code) {
                     $subfield->nodeValue = $value;
                     $done = true;
                     break;
                 }
             }
             if (!$done) {
                 $subfield = $this->xml->createElement("subfield");
                 $subfield->setAttribute("code",$code);
                 $subfield->appendChild($this->xml->createTextNode($value));
                 $fields[0]->appendChild($subfield);
             }
         }
     }
The documentation for this class was generated from the following file:
grimas/grima-lib.php