Grima: grimas/grima-lib.php File Reference
grima-lib.php File Reference
Classes
class Grima
grima-lib.php - a library for running API calls in Alma
class GrimaTask
The base class for most "grimas".
class GrimaTaskMessage
A thin wrapper around a message and urgency level.
class GrimaForm
A holder for the user inputs to a grima, base on the XML file.
class GrimaFormField
Wrapper for each field in a form, keeping track of its properties.
class AlmaObject
Base class for objects returned from alma APIs (mostly just array access)
class AlmaObjectWithMARC
Methods for fields and subfields in Alma's MARCXML.
class MARCField
MARC fields for use in bibs and holdings.
class MARCSubfield
class Bib
class HoldingsList
class HoldingsList
class HoldingsListEntry
class HoldingsListEntry
class ItemList
class ItemList
class Holding
class Holding
class Item
class Item
class ElectronicCollection
class ElectronicCollection
class ElectronicService
class ElectronicService
class ElectronicPortfolio
class ElectronicPortfolio
class Set
class Set IN PROGRESS
class SetMember
class SetMember
class Library
class Library
class Location
class Location
class AnalyticsReport
class AnalyticsReport
class GrimaDB
Shared access to the database for GrimaUser and GrimaInstitution.
class GrimaInstitution
Interface to the GrimaDB database to retrieve API keys.
class GrimaUser
Interface to the GrimaDB database to check password and get institution's apikey.
Functions
tableExists ($pdo, $table)
Variables
$grima = new Grima()
Function Documentation
tableExists()
tableExists ($pdo, $table)
Definition at line 3113 of file grima-lib.php.
Referenced by GrimaDB\init().
{
     $table_esc = "\"" . preg_replace( "/\"/", "\"\"", $table ) . "\"";
     try {
         $result = $pdo->query("SELECT 1 FROM $table_esc LIMIT 1");
     } catch (Exception $e) {
         // We got an exception == table not found
         return FALSE;
     }
     // Result is either boolean FALSE (no table found) or PDOStatement Object (table found)
     return $result !== FALSE;
 }
Variable Documentation
$grima
$grima = new Grima()
Definition at line 1166 of file grima-lib.php.
Referenced by ItemList\__construct(), Set\addMember(), Bib\addToAlma(), Holding\addToAlmaBib(), ElectronicPortfolio\addToAlmaBib(), Item\addToAlmaHolding(), ElectronicPortfolio\addToAlmaService(), GrimaTask\check_login(), Set\createFromImport(), Set\deleteAllMembers(), Bib\deleteAllPortfolios(), ElectronicService\deleteAllPortfolios(), Bib\deleteFromAlma(), Holding\deleteFromAlma(), Item\deleteFromAlma(), ElectronicPortfolio\deleteFromAlma(), Set\deleteFromAlma(), Bib\deleteTreeFromAlma(), Holding\deleteTreeFromAlma(), GrimaUser\GetCurrentUser(), HoldingsListEntry\getItemList(), Holding\getItemList(), Set\getMembers(), Holding\getMmsFromHoldingID(), Holding\getMmsIfNeeded(), Bib\getPortfolioList(), ElectronicService\getPortfolios(), ElectronicCollection\getServices(), Bib\loadFromAlma(), HoldingsList\loadFromAlma(), Holding\loadFromAlma(), Item\loadFromAlma(), ElectronicCollection\loadFromAlma(), ElectronicService\loadFromAlma(), ElectronicPortfolio\loadFromAlma(), Set\loadFromAlma(), Library\loadFromAlma(), Location\loadFromAlma(), Item\loadFromAlmaBarcode(), Item\loadFromAlmaBCorX(), Holding\loadFromAlmaX(), Item\loadFromAlmaX(), ElectronicPortfolio\loadFromAlmaX(), AnalyticsReport\runReport(), GrimaUser\SetCurrentUser(), Bib\updateAlma(), Holding\updateAlma(), Item\updateAlma(), and ElectronicPortfolio\updateAlma().