Grima: grimas/grima-util.php File Reference
grima-util.php File Reference
Functions
XMLtoWeb ($DOM)
importXML ($DOM, $xmlString)
appendInnerXML ($elt, $xmlString)
setInnerXML ($elt, $xmlString)
pauseAndAsk ()
do_redirect ($url)
bib_get ($mms_id)
mfhd_get ($mms_id, $holding_id)
join_paths (... $paths)
Function Documentation
appendInnerXML()
appendInnerXML ($elt, $xmlString)
Definition at line 20 of file grima-util.php.
References importXML().
Referenced by AlmaObjectWithMARC\appendField(), Holding\setCallNumber(), and setInnerXML().
{
     $DOM = $elt->ownerDocument;
     $frag = importXML( $DOM, $xmlString );
     $elt->appendChild( $frag );
 }
bib_get()
bib_get ($mms_id)
Definition at line 56 of file grima-util.php.
{
     require_once("grima-config.php");
     $url = $hostname . '/almaws/v1/bibs/{mms_id}';
     $ch = curl_init();
     $templateParamNames = array('{mms_id}');
     $templateParamValues = array(urlencode($mms_id));
     $url = str_replace($templateParamNames, $templateParamValues, $url);
     $queryParams = '?view=full&expand=None&apikey=' . urlencode($apikey);
     curl_setopt($ch, CURLOPT_URL, $url . $queryParams);
     curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
     curl_setopt($ch, CURLOPT_HEADER, FALSE);
     curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
     $response = curl_exec($ch);
     curl_close($ch);
     return $response;
 }
do_redirect()
do_redirect ($url)
Definition at line 45 of file grima-util.php.
Referenced by GrimaTask\call(), and GrimaTask\check_login().
{
     if(!headers_sent()) header("Location: $url");
     $url_html = htmlspecialchars($url);
 echo "<!DOCTYPE html><html><head><title>Redirect</title><meta http-equiv=refresh content='1; url=$url'></head><body><a href='$url_html'>Go here: $url_html</a></body></html>\n";
     exit;
 }
importXML()
importXML ($DOM, $xmlString)
Definition at line 14 of file grima-util.php.
Referenced by appendInnerXML().
{
     $frag = $DOM->createDocumentFragment();
     $frag->appendXML($xmlString);
     return $frag;
 }
join_paths()
join_paths ($paths)
Definition at line 114 of file grima-util.php.
Referenced by GrimaTask\__construct(), GrimaDB\getDb(), and Grima\session_init().
{
     return preg_replace('~[/\\\\]+~', DIRECTORY_SEPARATOR, implode(DIRECTORY_SEPARATOR, $paths));
 }
mfhd_get()
mfhd_get ($mms_id, $holding_id)
Definition at line 73 of file grima-util.php.
{
     require_once("grima-config.php");
     $url = $hostname . '/almaws/v1/bibs/{mms_id}/holdings/{holding_id}';
     $ch = curl_init();
     $templateParamNames = array('{mms_id}','{holding_id}');
     $templateParamValues = array(urlencode($mms_id,$holding_id));
     $url = str_replace($templateParamNames, $templateParamValues, $url);
     $queryParams = '?view=full&expand=None&apikey=' . urlencode($apikey);
     curl_setopt($ch, CURLOPT_URL, $url . $queryParams);
     curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
     curl_setopt($ch, CURLOPT_HEADER, FALSE);
     curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
     $response = curl_exec($ch);
     curl_close($ch);
     return $response;
 }
pauseAndAsk()
pauseAndAsk ()
Definition at line 32 of file grima-util.php.
{
     echo "Are you sure you want to do this?  Type 'yes' to continue: ";
     $handle = fopen ("php://stdin","r");
     $line = fgets($handle);
     if(trim($line) != 'yes'){
         echo "ABORTING!\n";
         exit;
     }
     fclose($handle);
     echo "\n";
     echo "Thank you, continuing...\n";
 }
setInnerXML()
setInnerXML ($elt, $xmlString)
Definition at line 26 of file grima-util.php.
References appendInnerXML().
{
     while( $elt->hasChildNodes() )
         $elt->removeChild( $elt->lastChild );
     appendInnerXML( $elt, $xmlString );
 }
XMLtoWeb()
XMLtoWeb ($DOM)
Definition at line 7 of file grima-util.php.
{
     header('Content-Type: text/plain');
     $DOM->preserveWhiteSpace = false;
     $DOM->formatOutput = true;
     print $DOM->saveXML();
 }